spring:
  redis:
    timeout: 6000
    database: 2
    lettuce:
      pool:
        max-active: 50
        max-wait: -1
        max-idle: 20
        min-idle: 2
      #sentinel哨兵配置
    sentinel:
      master: mymaster
      nodes: 172.17.153.1830:26379,172.17.232.1680:26379,172.17.232.1670:26379
    password: xluniccc

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://prod:prod@172.17.153.1830:8761/eureka/,http://prod:prod@172.17.232.1680:8761/eureka/
