info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@

spring:
  #该配置文件中的配置，对应的服务名称是 xl-gateway
  application:
    name: xl-gateway
  profiles:
    active: qa
  jackson:
    serialization.indent_output: true
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/xl-dam/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      httpclient:
        connectTimeout: 1000
        responseTimeout: 6000
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      - name: RequestRateLimiter
        args:
          redis-rate-limiter.replenishRate: 20  #流速 每秒
          redis-rate-limiter.burstCapacity: 100   #令牌桶的容积
          rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
          key-resolver: "#{@apiKeyResolver}" #SPEL表达式去的对应的bean
      - name: Retry
        args:
          retries: 3 #重试次数，不包含本次，默认是3
          statuses: BAD_GATEWAY,NOT_FOUND #org.springframework.http.HttpStatus
          methods: GET
          backoff:
            firstBackoff: 10ms
            maxBackoff: 50ms
            factor: 2
            basedOnPreviousValue: false
      discovery:
        locator:
          enabled: false # 开启注册发现服务动态路由
          lowerCaseServiceId: true #启用服务实例id名称小写支持
      routes:
      - id: authorization_route
        uri: lb://xl-authorization
        predicates:
          - Path=/xl-auth/api/**
        filters:
          - StripPrefix=2
      - id: authentication_route
        uri: lb://xl-authentication
        predicates:
          - Path=/xl-authentication/**
        filters:
          - StripPrefix=1
      - id: das_route
        uri: lb://xl-das888
        predicates:
          - Path=/xl-das/**
        filters:
          - StripPrefix=1
          - Auth
          - name: Hystrix
            args:
              name: tycFallback
              fallbackUri: forward:/fallback/tyc

      - id: dcs_route
        uri: lb://xl-dcs
        predicates:
          - Path=/xl-dcs/**
        filters:
        - StripPrefix=1
      - id: dam_route
        uri: lb://xl-dam
        predicates:
          - Path=/xl-dam/**
        filters:
          - StripPrefix=1

#端口
server:
  port: 8001
# Hystrix 配置
hystrix:
  command:
    default:
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 500
      execution:
        isolation:
          semaphore:
            maxConcurrentRequests: 1000
          thread:
            timeoutInMilliseconds: 5000
#监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

#Eureka相关配置
eureka:
    client:
        instance-info-replication-interval-seconds: 5 #复制实例变化信息到eureka服务器所需要的时间间隔（s），默认为30秒
        registry-fetch-interval-seconds: 5 #从Eureka服务器端获取注册信息的间隔时间，单位：秒
    instance:
        prefer-ip-address: true
        instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        lease-renewal-interval-in-seconds: 5 # eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒
        lease-expiration-duration-in-seconds: 10 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
#        status-page-url-path: ${spring.management.context-path}/info
#        health-check-url-path: ${spring.management.context-path}/health


feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true
